package Hangman;


public class Gameword {

	private String word;
	private String[] wordArray = 
			{"abruptly",
			"absurd",
			"abyss",
			"affix", 
			"askew", 
			"avenue", 
			"awkward", 
			"axiom",
			"azure",
			"bagpipes",
			"bandwagon",
			"banjo",
			"bayou",
			"beekeeper",
			"bikini",
			"blitz",
			"blizzard",
			"boggle",
			"bookworm",
			"boxcar",
			"boxful",
			"buckaroo",
			"buffalo",
			"buffoon",
			"buxom",
			"buzzard",
			"buzzing",
			"buzzwords",
			"caliph",
			"cobweb",
			"cockiness",
			"croquet",
			"crypt",
			"curacao",
			"cycle",
			"daiquiri",
			"dirndl",
			"disavow",
			"dizzying",
			"duplex",
			"dwarves",
			"embezzle",
			"equip",
			"espionage",
			"exodus",
			"faking",
			"fishhook",
			"fixable",
			"fjord",
			"flapjack",
			"flopping",
			"fluffiness",
			"flyby",
			"foxglove",
			"frazzled",
			"frizzled",
			"fuchsia",
			"funny",
			"gabby",
			"galaxy",
			"galvanize",
			"gazebo",
			"gizmo",
			"glowworm",
			"glyph", 
			"gnarly",
			"gnostic",
			"gossip",
			"grogginess",
			"haiku",
			"haphazard",
			"hyphen",
			"icebox",
			"injury",
			"ivory",
			"ivy",
			"jackpot",
			"jaundice",
			"jawbreaker",
			"jaywalk",
			"jazziest",
			"jazzy",
			"jelly",
			"jigsaw",
			"jinx",
			"jiujitsu",
			"jockey",
			"jogging",
			"joking",
			"jovial",
			"joyful",
			"juicy",
			"jukebox",
			"jumbo",
			"kayak",
			"kazoo",
			"keyhole",
			"khaki",
			"kilobyte",
			"kiosk",
			"kitsch",
			"kiwifruit",
			"klutz",
			"knapsack",
			"larynx",
			"lengths",
			"lucky",
			"luxury",
			"lymph",
			"marquis",
			"matrix",
			"megahertz",
			"microwave",
			"mnemonic",
			"mystify",
			"nightclub",
			"nowadays",
			"numbskull",
			"nymph",
			"onyx",
			"ovary",
			"oxidize",
			"oxygen",
			"pajama",
			"peekaboo",
			"phlegm",
			"pixel",
			"pizazz",
			"pneumonia",
			"polka",
			"psyche",
			"puppy",
			"puzzling",
			"quartz",
			"queue",
			"quips",
			"quiz",
			"quizzes",
			"rhubarb",
			"rhythm",
			"rickshaw",
			"schnapps",
			"scratch",
			"shiv",
			"snazzy",
			"sphinx",
			"spritz",
			"squawk",
			"staff",
			"strength",
			"strengths",
			"stretch",
			"stronghold",
			"stymied",
			"subway",
			"swivel",
			"syndrome",
			"thumbscrew",
			"topaz",
			"transcript",
			"transgress",
			"transplant",
			"twelfth",
			"twelfths",
			"unknown",
			"unworthy",
			"unzip",
			"uptown",
			"vaporize",
			"vixen",
			"vodka",
			"voodoo",
			"vortex",
			"voyeurism",
			"walkway",
			"waltz",
			"wave",
			"wavy",
			"waxy",
			"wellspring",
			"wheezy",
			"whiskey",
			"whizzing",
			"whomever",
			"wimpy",
			"witchcraft",
			"wizard",
			"woozy",
			"wristwatch",
			"xylophone",
			"yachtsman",
			"youthful",
			"yummy",
			"zephyr",
			"zigzag",
			"zigzagging",
			"zilch",
			"zipper",
			"zodiac",
			"zombie"};
	//200 words in this array
	
	public String getRandomWord() {
		int randomIndex = (int)(Math.random() * (wordArray.length + 1));
		word = (wordArray[randomIndex]);
		return word;
	}
	
		// using Math.random:
//		int min = 0;
//		int max = wordArray.length;
//		int randomInt = (int)(Math.random() * (max - min + 1) + min);
//		System.out.println(randomInt);
		
		// using Random Class:
//		Random r=new Random(); 
//		int randomNumber=r.nextInt(wordArray.length);
//		word = (wordArray[randomNumber]);
//		System.out.println(wordArray.length);
	
}
